<?php
/** @var $block Magento\Framework\View\Element\Template 
*/
/**
 * @var $phoneNumberViewModel Juno\Theme\ViewModel\PhoneNumber
 */
/**
 * @var $phoneNumberViewModel Juno\Theme\ViewModel\PhoneNumber
 */

    $phoneNumberViewModel = $block->getData('phone_number_view_model');
?>
<div class="phone-number" data-aos="fade-down">
<?= __('Phone number: %1', $escaper->escapeHtml($phoneNumberViewModel->getPhoneNumber())) ?>
    <?= $block->getBaseUrl()?>
</div>  